defaults:
  - default_lcnn
name: lightcnn-lfcc
spec_processing:
  _target_: antispoof.frontend.LFCC
  n_dim: 60
  sr: ${trainer.sr}
  speckwargs:
    n_fft: 512
    win_length: 320
    hop_length: 160
kaiman: True
arch:
  _target_: antispoof.model.LightCNNTrim
  backbone:
    _target_: antispoof.model.LightCNNBackbone
    dropout: 0.75
    kaiman: ${kaiman}
  head:
    _target_: antispoof.model.LinearHead
    ifc: 4416
    dropout: 0.75
    kaiman: ${kaiman}
  softmax:
    _target_: antispoof.model.NormalSoftmax
loss:
  _target_: antispoof.loss.CELoss