defaults:
  - default_lcnn
name: lightcnn-stft
spec_processing:
  _target_: antispoof.frontend.STFT2
kaiman: False
arch:
  _target_: antispoof.model.LightCNNTrim
  backbone:
    _target_: antispoof.model.LightCNNBackbone
    dropout: 0.75
    kaiman: ${kaiman}
  head:
    _target_: antispoof.model.LinearHead
    ifc: 23552
    dropout: 0.75
    kaiman: ${kaiman}
  softmax:
    _target_: antispoof.model.NormalSoftmax
loss:
  _target_: antispoof.loss.CELoss
  weight:
  - 9.0
  - 1.0