name: lightcnn-lfcc
logger:
  _target_: antispoof.logger.logger.get_logger
  experiment_name: ${name}
  name: train
  save_dir: ${trainer.save_dir}
spec_processing:
  _target_: antispoof.utils.LFCC
  n_dim: 60
  sr: ${trainer.sr}
  speckwargs:
    n_fft: 512
    win_length: 320
    hop_length: 160
data:
  train:
    _target_: torch.utils.data.DataLoader
    batch_size: 64
    num_workers: 10
    shuffle: True
    drop_last: False
    collate_fn: 
      _target_: antispoof.collate_fn.get_collate_fn
    dataset:
      _target_: antispoof.datasets.LADataset
      part: train
      sr: ${trainer.sr}
      spec_processing: ${spec_processing}
      spec_segment_length: 750
  val:
    _target_: torch.utils.data.DataLoader
    batch_size: 64
    num_workers: 10
    shuffle: False
    drop_last: False
    collate_fn: 
      _target_: antispoof.collate_fn.get_collate_fn
    dataset:
      _target_: antispoof.datasets.LADataset
      part: dev
      sr: ${trainer.sr}
      spec_processing: ${spec_processing}
      spec_segment_length: 750
  test:
    _target_: torch.utils.data.DataLoader
    batch_size: 64
    num_workers: 10
    shuffle: False
    drop_last: False
    collate_fn: 
      _target_: antispoof.collate_fn.get_collate_fn
    dataset:
      _target_: antispoof.datasets.LADataset
      part: eval
      sr: ${trainer.sr}
      spec_processing: ${spec_processing}
      spec_segment_length: 750
metrics:
  - _target_: antispoof.metric.Accuracy
device: 
  _target_: torch.device
  device: "cuda:0"
arch:
  _target_: antispoof.model.LightCNN
  ifc_size: 4416
  dropout_p: 0.75
  dropout_fc: 0.75
  sr: ${trainer.sr}
  banks: False
loss:
  _target_: antispoof.loss.CELoss
  weight:
  - 9.0
  - 1.0
lr_scheduler:
  _target_: antispoof.scheduler.getExponentialScheduler
  gamma: 0.707
optimizer:
  _target_: torch.optim.Adam
  betas:
    - 0.9
    - 0.999
  eps: 0.00000001
  lr: 0.0003
trainer:
  _target_: antispoof.trainer.Trainer
  epochs: 30
  save_period: 1
  verbosity: 2
  save_dir: saved/${name}/
  visualize: wandb
  wandb_project: antispoof_project
  monitor: min val_loss
  scheduler_steps: 25
  sr: 16000
  len_epoch: 1985